code = (reaction | definition)*
definition = ELEMENT ":" reaction ;
reaction = molecule ("+" molecule)* "->" molecule ("+" molecule)*
molecule = NUMBER? atom+ ; 
atom     = ELEMENT | ELEMENT subscript ;
subscript = "_" NUMBER ;

NUMBER   = "[0-9]+" ;
ELEMENT  = "[A-Z][a-z]+" ;
COMMENT  = ";" text "\n" ;