program  ::= equation*
equation ::= reagent '->' reagent '.'
reagent  ::= term ('+' term)*
term     ::= NUMBER? molecule+
molecule ::= molContents ('_' NUMBER)?
molContents ::= '(' molecule ')' | ELEMENT | literal
literal  ::= ELEMENT['H'] (numberLiteral | booleanLiteral | stringLiteral | pairLiteral | listLiteral | mapLiteral)
numberLiteral  ::= '^' NUMBER
booleanLiteral ::= 'Tr' | 'Fa'
stringLiteral  ::= '"' any chars except for double quote, except when escaped '"'
pairLiteral    ::= '<' literal ',' literal '>'
listLiteral    ::= '[' (literal (',' literal)?)? ']'
mapLiteral     ::= '{' (literal ':' literal (',' literal ':' literal)?)? '}'

comment ::= ';' text '\n'

NUMBER ::= "'-'?[0-9]+"
ELEMENT ::= "[A-Z][a-z]*"
